export const footer = [
  ["Contact", "FAQ's"],
  ["Tutorials", "Blog"],
  ["Privacy", "Banned Items"],
  ["About", "Jobs"],
  ["Facebook", "Twitter", "Linkedin"],
];
export const features = [
  [
    "Search",
    "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
  ],
  [
    "Select",
    "Choose from thousands of options generated by the slogan maker that fit your needs.",
  ],
  ["Stand out", "Congrats on your new slogan. It's time to win the world!"],
];
export const products = [
  [
    "Privacy Policy Generator",
    "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
  ],
  [
    "Terms & Conditions Generator",
    "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
  ],
  [
    "Domain Name Generator",
    "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
  ],
  [
    "Invoice Generator",
    "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
  ],
];
export const slogans = [
  "There is no Sore it will Not Heal, No cool it will not Subdue.",
  "Review the facts cool is the best.",
  "coziness building for tomorrow",
];
